### ISSUE TITLE
Default formatprog when multiple are present - README

### ISSUE THREAD

**Issue by bondhugula** [vim-autoformat/vim-autoformat#342]
Hello,

The README states:
```
Here is a list of formatprograms that are supported by default, and thus will be detected and used by vim when they are installed properly.
```
It's not clear from this description as to which format program will be used when there are multiple ones in `formatterpath` - for eg., if both autopep8 and yapf exist. Could this be clarified?

**Comment by Chiel92** [comment]
Feel free to propose any clarifications in a PR

**Comment by bondhugula** [comment]
> Feel free to propose any clarifications in a PR

But I wouldn't know what the answer/clarification to it is. Even with the verbose mode and messages, I couldn't tell which formatter was being used.

**Comment by Chiel92** [comment]
The lists of default formatters are defined in https://github.com/Chiel92/vim-autoformat/blob/master/plugin/defaults.vim
They are just tried in order
