### ISSUE TITLE
E195: Cannot open viminfo file for reading 

### ISSUE THREAD

**Issue by simin75simin** [vim-autoformat/vim-autoformat#354]
os: ubuntu 18
vim: 8.2
python: 3.7.9

followed the instruction and did not use any formatter of my own (using default formatter). 

when i type ```:Autoformat``` into the vim console, it indented my python code and produced that error.

help please.

**Comment by Chiel92** [comment]
That error is not related to this plugin, but it is a problem with your setup. You'll have to find out why your viminfo file can't be written.
