### ISSUE TITLE
Not an editor command: ^M when install via Plug

### ISSUE THREAD

**Issue by harttle** [vim-autoformat/vim-autoformat#355]
I've been using this for years in MacOS, now I switched to Windows and using this in WSL Ubuntu. When installing this plugin by [vim-plug](https://github.com/junegunn/vim-plug):

```vim
Plug 'Chiel92/vim-autoformat'
```

Run `vim +PlugInstall` in bash get errors like:

```
line  384:
E488: Trailing characters
Error detected while processing /home/harttle/.vim/plugged/vim-autoformat/plugin/defaults.vim:
line    1:
E492: Not an editor command: ^M
line    5:
E492: Not an editor command: ^M
line    6:
E492: Not an editor command: ^M
line    8:
E15: Invalid expression: !exists('g:autoformat_autoindent')^M
line  709:
E171: Missing :endif
Error detected while processing /home/harttle/.vim/plugged/vim-autoformat/plugin/utils.vim:
```

I believe it's caused by the CRLF fileformat in `vim-autoformat/plugin/*`. Anyone thoughts on what I'm doing wrong or how to work around this?

**Comment by Chiel92** [comment]
Related: https://github.com/vim/vim/issues/6156

**Comment by Chiel92** [comment]
I also use vim on WSL btw, and don't experience this problem. The line endings are `lf` for me. Since this is not a vim-autoformat specific issue I'm going to close it.

**Comment by Chiel92** [comment]
For reference and troubleshooting: our gitattributes file is properly defined: https://github.com/vim-autoformat/vim-autoformat/blob/master/.gitattributes

**Comment by harttle** [comment]
Update: I somewhat cloned it in windows powershell or with Git for win64, I believe that's the root cause. Remove and reinstall fixes my problem.
