### ISSUE TITLE
Vim-autoformat can not find _clang-format in window 10

### ISSUE THREAD

**Issue by Hungpro3112** [vim-autoformat/vim-autoformat#360]
I use windows 10 and my vim version is 8.2
I put my _clang-format in my main project directory but is not work.
Here are messages when i use verbose mode
![image](https://user-images.githubusercontent.com/75968004/127420428-40dc3cb7-5c9b-4aef-9870-dd772c5ad892.png)
How to fix this problem? Thanks for your help !!!

**Comment by chtenb** [comment]
That means the clang-format isn't in your path. Read the first section of "How to use" in the README: https://github.com/vim-autoformat/vim-autoformat#how-to-use

**Comment by Hungpro3112** [comment]
I put this line in my _vimrc but it doesn't work 
![image](https://user-images.githubusercontent.com/75968004/127598116-6b1926d1-f726-4768-9735-85c8cc3f4bb6.png)

**Comment by Hungpro3112** [comment]
![image](https://user-images.githubusercontent.com/75968004/127603920-9229ffa2-4cda-45e4-aa00-91a3283f7764.png)
I put it in _vimrc but doesn't work
Where did I go wrong?
I downloaded clang-format and extracted it
![image](https://user-images.githubusercontent.com/75968004/127604222-95c22f97-ed49-4ffb-8541-90a573cb41df.png)

**Comment by chtenb** [comment]
Does the clang-format folder contain the clang-format executable?

**Comment by Hungpro3112** [comment]
> Does the clang-format folder contain the clang-format executable?

I download it from the main site but it doesn't have. I think i'm wrong. 
Can you show how to install clang-format ? Sorry I'm new with this thing

**Comment by chtenb** [comment]
I'm not the right person to ask as I don't use clang-format myself. But you'll have to figure out how to install the executable and not download and extract the source code, which is what you did above from the looks of it.
