### ISSUE TITLE
How to use black formatter for python

### ISSUE THREAD

**Issue by HungPham3112** [vim-autoformat/vim-autoformat#362]
I have absolute path for python formating use black:

```
let g:formaterpath=['C:\Program Files\LLVM\bin\clang-format.exe',
            \ 'C:\Users\MyPC\.cargo\bin\cargo-fmt.exe', 
            \ 'C:\Users\MyPC\Python_project\Scripts\black.exe',]

```

but when I use `:Autoformat` it used `autopep8` instead of `black`

> Messages maintainer: Bram Moolenaar <Bram@vim.org>
> 
> "Python_project\for.py" 22 lines, 397 bytes
> Already at newest change
> Selected formatter: autopep8

**Comment by chtenb** [comment]
That's because autopep8 is tried first, and if it succeeds it stops there.
Try setting

```
let g:formatters_python = ['black']
```
