### ISSUE TITLE
don't add indent for array in yaml 

### ISSUE THREAD

**Issue by winkee01** [vim-autoformat/vim-autoformat#370]
do you support customization the autoformat for yaml file? I prefer no adding indent for array in yaml.

![image](https://user-images.githubusercontent.com/49930785/156323094-c3588aba-45de-41ad-ad5e-1b516d34752c.png)

related threads:
https://github.com/redhat-developer/vscode-yaml/issues/172
https://github.com/prettier/prettier/pull/10927

**Comment by chtenb** [comment]
Yeah, we do support customization. Read the readme on how to pass CLI arguments to the formatter.

**Comment by chtenb** [comment]
Exactly
