### ISSUE TITLE
eslint fails when rules apply on temporary filename

### ISSUE THREAD

**Issue by gautaz** [vim-autoformat/vim-autoformat#381]
Hello,

We use eslint rules to also enforce filenames (kebab-case is mandatory and abbreviations are forbidden).

Hence when using autoformat, eslint fails with:

```
original-filename.js_eslint_tmp_0.js
  1:1  error  Filename is not in kebab case. Rename it to `original-filename.js-eslint-tmp-0.js`  unicorn/filename-case
  3:1  error  The filename `original-filename.js_eslint_tmp_0.js` should be named `original-filename.js_eslint_temporary_0.js`. A more descriptive name will do too  unicorn/prevent-abbreviations
```

Has anyone any idea on how to cope with this issue with the current autoformat implementation?

Is there a way to customize the name of the temporary file?

Another option would be to use a more neutral filename like `temporary<number>.<original file extension>` to avoid (partially) these types of issues.

**Comment by gautaz** [comment]
Fixing #357 would also fix this issue.
Sorry I wasn't able to work on it in the meantime... :cry:

**Comment by chtenb** [comment]
Fixing https://github.com/vim-autoformat/vim-autoformat/issues/357 would of course be a good way to solve this, but I'd also merge a change of the filename being used to something simpler.

**Comment by gautaz** [comment]
Spring cleaning time!
There is no need to keep this issue anymore, feel free to reopen a new one if needed.
