### ISSUE TITLE
how to autopep8 a python file to --max-line-length 80

### ISSUE THREAD

**Issue by huangyingw** [vim-autoformat/vim-autoformat#384]
currently, it doesn't work, how to make this happen?
I could change in my private branch.

**Comment by chtenb** [comment]
I think you just have to set the &textwidth property in your buffer?

**Comment by huangyingw** [comment]
how to set this to all *.py files?
I don't want to only set this to one buffer, which means I need to set buffer by buffer.

**Comment by chtenb** [comment]
Use an autocommand. You can google or ask chatgpt on how to do this. It's a pretty common thing :)
