### ISSUE TITLE
Failed to format part of the code with clang-format

### ISSUE THREAD

**Issue by onlycalm** [vim-autoformat/vim-autoformat#385]
The configuration of .vimrc is as follows:

```vimscript
"vim-autoformat/vim-autoformat
let g:formatdef_clangformat_google = '"clang-format -style google -"'
let g:formatters_c = ['clangformat_google']
let g:autoformat_autoindent = 0
let g:autoformat_retab = 0
let g:autoformat_verbosemode = 1
let g:autoformat_remove_trailing_spaces = 1
```

Methods of reproducing problems:

1. Select a code block in visual mode and execute instructions `:Autoformat` . 
2. Execute Instructions ` AutoformatLine` .

It will format the entire C file, rather than just part of the code block.

**Comment by chtenb** [comment]
Look at the default definition to see how to pass the range arguments to clang.
