### ISSUE TITLE
Plugin randomly indents Python code in case of error

### ISSUE THREAD

**Issue by A-tA-v** [vim-autoformat/vim-autoformat#389]
(1) I have experienced a dangerous behaviour of this plugin. If there is an error in the code, the plugin can arbitrary indent dozens of lines below. This can have very serious consequences. I have to inspect the code carefully, and it is easy to overlook something. I would inspect that upon error detection the plugin does not do anything but generates a report.

**Comment by chtenb** [comment]
You can disable this, see https://github.com/vim-autoformat/vim-autoformat#how-to-use

**Comment by A-tA-v** [comment]
Thanks you for suggestion. I added these lines:
```
let g:autoformat_autoindent = 0
let g:autoformat_retab = 0
let g:autoformat_remove_trailing_spaces = 1
```
and it seems to work fine.
