### ISSUE TITLE
 Ruff support

### ISSUE THREAD

**Issue by debeetle** [vim-autoformat/vim-autoformat#391]
It seems that this cannot support ruff (a python linter). Does it be possible to using ruff formator?

**Comment by chtenb** [comment]
Yes, but you'll have to configure it yourself. See the README.

**Comment by debeetle** [comment]
I did go through the README, and I tried `let g:formatters_python = ['ruff']`. However it does not work. Certainly I have `let g:python3_host_prog="/usr/bin/python3` in configuration. And for making sure that it won't fallback to vim's indent file, retabbing and removing trailing whitespace, I also followed the doc.
Here's the Error if it helps:
`Error detected while processing function <SNR>41_TryAllFormatters:
line   35:
No format definition found in 'g:formatdef_ruff'.
`

**Comment by chtenb** [comment]
I think you missed some steps in the README, about defining the actual formatting command `g:formatdef_ruff`.
