### ISSUE TITLE
Error detected while processing BufWrite Autocommands for "*":

### ISSUE THREAD

**Issue by lemorage** [vim-autoformat/vim-autoformat#395]
After adding this config `au BufWrite * :Autoformat` to my `.vimrc`, I got the following errors whenever I saved my file. Is there anything wrong?

```
E195: Cannot open viminfo file for reading
Error detected while processing BufWrite Autocommands for "*":
```

**Comment by chtenb** [comment]
Sounds unrelated to this plugin and more like a general problem in your vim setup. I would investigate why your vim info file cannot be written.
